set number
set relativenumber
set autoindent
set smartindent
set exrc
set nohlsearch
set hidden
set noerrorbells
set tabstop=4
set softtabstop=4
set shiftwidth=4
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=/tmp/
set undofile
set incsearch
set fillchars=
set laststatus=2
set termguicolors
set showtabline=2
color slate
